// src/home/_mock.js
import { LOBBY_STATUS, LOBBY_STATUS_TEXT } from '../lobby/constants/lobbyStatus';

export const lobbyCardsMockData = [
  {
    id: '1',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.REGISTERING,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.REGISTERING],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 30,
    maxPlayers: 40,
    isRegistered: true,
    isVip: true,
    schedule: 'امروز ۱۷:۳۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'multiplayer',
    team_type: 4,
  },
  {
    id: '2',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.FULL,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.FULL],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 40,
    maxPlayers: 40,
    isVip: false,
    schedule: 'امروز ۱۸:۰۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'multiplayer',
    team_type: 3,
  },
  {
    id: '3',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.RUNNING,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.RUNNING],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 30,
    maxPlayers: 40,
    isVip: true,
    schedule: 'امروز ۱۹:۰۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'battle_royale',
    team_type: 1,
  },
  {
    id: '4',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.RUNNING,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.RUNNING],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 35,
    maxPlayers: 40,
    isVip: false,
    schedule: 'امروز ۲۰:۰۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'multiplayer',
    team_type: 5,
  },
  {
    id: '5',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.FINISHED,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.FINISHED],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 40,
    maxPlayers: 40,
    isVip: false,
    schedule: 'امروز ۲۱:۰۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'battle_royale',
    team_type: 2,
  },
  {
    id: '6',
    title: 'آیزولیتد ۴۰ نفره جایگاهی',
    status: LOBBY_STATUS.CANCELED,
    statusText: LOBBY_STATUS_TEXT[LOBBY_STATUS.CANCELED],
    entryFee: '۱۰۰,۰۰۰ تومن',
    prize: '۱۰,۰۰۰,۰۰۰ تومن',
    currentPlayers: 25,
    maxPlayers: 40,
    isVip: true,
    schedule: 'امروز ۲۲:۰۰',
    tags: ['اسکوادی', 'اتوریوایو', 'جایگاهی'],
    game_mode: 'multiplayer',
    team_type: 2,
  },
];

export const myLobbiesMockData = lobbyCardsMockData.filter((l) => l.isRegistered);
export const allLobbiesMockData = lobbyCardsMockData;
